### ISSUE TITLE
Question: how to pass in data > 65,535 bytes

### ISSUE THREAD

**Issue by ostinelli** [igrigorik/http-2#57]
Hi Ilya,
I'm trying to understand how to pass in data > 65,535 bytes.

When I issue the following response from a server:

```ruby
conn.on(:stream) do |stream|

  # [...]

  body = "a" * 100_000
  headers = { ':content-length' => 100_000 } # snippet
  stream.headers(headers, end_stream: false)
  stream.data(body, end_stream: true)
end
```

Then on the receiving end (the client) I have:

```ruby
stream.on(:data) do |data|
  p data.length
end
````
Which prints out:

```
16384
16384
16384
16383
```

which sums up to 65,535, the default window size, after which my client hangs waiting for more data (that never comes).

I have read about flow control but I'm not understanding if I'm supposed to change the window size on the fly (on the server?), or if I need to create a second stream with the remaining size of the data. If it's the first option, the [README](https://github.com/igrigorik/http-2/blob/987e874150e9be8f813971f64c98f8996be27185/README.md) file states to use:

```ruby
stream.window_update(2048)
```
which is however an `undefined method 'window_update' for #<HTTP2::Stream:0x007fd9cd18f548>`, or a:

```ruby
conn.settings(streams: 100, window: Float::INFINITY)
```
which raises an `HTTP2::Error::CompressionError: Unknown settings ID for ` error.

Can you please advise? Thank you.

**Comment by igrigorik** [comment]
@ostinelli doh, you ran into https://github.com/igrigorik/http-2/issues/27. Specifically, the client doesn't auto-emit window-updates, which is why the server pauses. As a temporary fix, try applying this patch: https://github.com/lepidum/http-2/commit/c37100ca80db64f24704c9e86a90f72a5d9528f7. 

I'll wait for @mad-p or @tbetbetbe to respond.. If I don't hear back in a few days, I'll go ahead and merge one of their patches and update things on this end.

**Comment by ostinelli** [comment]
Thank you @igrigorik.

**Comment by igrigorik** [comment]
@ostinelli can you please try with latest code in master? I've merged https://github.com/igrigorik/http-2/commit/5148cb74819ffda6fe60354e610716fb30b5d74b and https://github.com/igrigorik/http-2/commit/8b62f88218254cd44ddd84bc6003fcab331851e9, which should (in theory) resolve your issue.

**Comment by ostinelli** [comment]
@igrigorik thank you. Good news: all tests of clients _receiving_ big bodies from the server pass now.

However, the tests of clients _sending_ big bodies still do not pass. I don't know if this is related or not, or if I'm doing something wrong, hence I'm just raising it here.

On the client I have:
```ruby
stream = conn.new_stream

conn.on(:frame) do |bytes|
  puts "PIPE: #{bytes.length}"
end

body = "a" * 100_000
headers = {
  ":scheme"=>"http",
  ":method"=>"POST",
  ":path"=>"/path",
  "host"=>"localhost",
  "content-length"=>"100000"
}

stream.headers(headers, end_stream: false)
stream.data(body, end_stream: true)
```

This sends some data:
```
PIPE: 24
PIPE: 15
PIPE: 31
PIPE: 16393
PIPE: 9
```

Then everything hangs.

On the server, this never gets called:
```ruby
conn.on(:stream) do |stream|
  stream.on(:data) { |data| p data }
end
```

Can you please hint me here? :)

**Comment by igrigorik** [comment]
@ostinelli can you log the sent and received frames + payloads? A couple of obvious questions:

- Are you writing the data out to the socket on the client? ;-)
- Does the server receive HEADERS frame? Which frames does it see?
- Nitpick: use :authority instead of `Host` - see http://httpwg.org/specs/rfc7540.html#rfc.section.8.1.2.3.

**Comment by ostinelli** [comment]
> Are you writing the data out to the socket on the client? ;-)

:)

> Does the server receive HEADERS frame? Which frames does it see?

Yes, it receives these headers:

```ruby
[[":scheme", "http"], [":method", "POST"], [":path", "/path"], ["host", "localhost"], ["content-length", "100000"]]
```
However, the server never has the `stream.on(:data)` callback triggered.

This is the sequence of frames:
```
CLIENT Sent frame: {:type=>:settings, :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100]]}
CLIENT Sent frame: {:type=>:headers, :flags=>[:end_headers], :payload=>[[":scheme", "http"], [":method", "POST"], [":path", "/path"], ["host", "localhost"], ["content-length", "100000"]], :stream=>1}
CLIENT Sent frame: {:type=>:data, :flags=>[], :payload=>"aaaaaaaaaaaaa...aaa [omitted, for a total of 16,385 bytes", :stream=>1}

SERVER Sent frame: {:type=>:settings, :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100]]}

CLIENT Received frame: {:length=>6, :type=>:settings, :flags=>[], :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100]]}
CLIENT Sent frame: {:type=>:settings, :stream=>0, :payload=>[], :flags=>[:ack]}

SERVER Received frame: {:length=>6, :type=>:settings, :flags=>[], :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100]]}
SERVER Sent frame: {:type=>:settings, :stream=>0, :payload=>[], :flags=>[:ack]}
SERVER Received frame: {:length=>22, :type=>:headers, :flags=>[:end_headers], :stream=>1, :payload=>"\x86\x83D\x84b\xB1\xA6\x7Ff\x86\xA0\xE4\x1D\x13\x9D\t\\\x84\b\x00\x00\x03"}

SERVER HEADERS RECEIVED: [[":scheme", "http"], [":method", "POST"], [":path", "/path"], ["host", "localhost"], ["content-length", "100000"]]
```
I've set up [this branch of NetHttp2](https://github.com/ostinelli/net-http2/tree/bodies_64) to demonstrate, just in case you want to see this yourself. The hanging test is [this one](https://github.com/ostinelli/net-http2/blob/bodies_64/spec/api/sending_sync_requests_spec.rb#L137).

To my understanding, the client is only sending 16,385 bytes in the data payload, and then closes the stream. Since the headers specify a content length of 100,000, the server just hangs waiting for more.

Is there anything that I'm missing there to ensure the client sends data?

> Nitpick: use :authority instead of Host - see http://httpwg.org/specs/rfc7540.html#rfc.section.8.1.2.3.

Nice, thank you.

**Comment by ostinelli** [comment]
I think that I can reproduce it by using just your gem.

```ruby
require 'http/2'

def try(length)
  conn = HTTP2::Client.new

  body = "a" * length
  headers = { ':content-length' => length.to_s }

  total_body_bytes = 0
  conn.on(:frame_sent) do |frame|
    total_body_bytes += frame[:payload].length if frame[:type] == :data
  end

  stream = conn.new_stream
  stream.headers(headers, end_stream: false)
  stream.data(body, end_stream: true)

  sleep 5

  total_body_bytes
end

[5_000, 50_000, 100_000, 200_000].each do |length|
  puts "For #{length} bytes of the body => total bytes of data in sent frames: #{try(length)}"
end
```

This outputs:

```
For 5000 bytes of the body => total bytes of data in sent frames: 5000
For 50000 bytes of the body => total bytes of data in sent frames: 50000
For 100000 bytes of the body => total bytes of data in sent frames: 65535
For 200000 bytes of the body => total bytes of data in sent frames: 65535
```

As you can see, the rest of the body > 65,535 is not being sent.

Am I not calling this properly? Does the client need to receive some kind of trigger from the server to continue sending data? If so, how?

Thank you for your inputs :)

**Comment by igrigorik** [comment]
> For 5000 bytes body => total bytes of data in sent frames: 5000
> For 50000 bytes body => total bytes of data in sent frames: 50000
> For 100000 bytes body => total bytes of data in sent frames: 65535
> For 200000 bytes body => total bytes of data in sent frames: 65535

That's exactly what you should expect to see. The default stream flow control window size is 65KB, so the client will pause sending data after 65kb, until it receives a window_update.

Looking at the spec you linked earlier... If I decrease the body size to ~10KB, I see the spec pass and fail semi-randomly, which is making me suspect of some race condition in the code. In the cases where it hands, I don't see your client code writing out the body data.

**Comment by ostinelli** [comment]
> That's exactly what you should expect to see. The default stream flow control window size is 65KB, so the client will pause sending data after 65kb, until it receives a window_update.

Indeed, but I couldn't do that until you [exposed the window_update method](https://github.com/igrigorik/http-2/commit/8b62f88218254cd44ddd84bc6003fcab331851e9) (which I reported as undefined in the issue). So thank you for fixing this in master :)

> Looking at the spec you linked earlier... If I decrease the body size to ~10KB, I see the spec pass and fail semi-randomly, which is making me suspect of some race condition in the code. In the cases where it hangs, I don't see your client code writing out the body data.

It is unclear to me if it's related to the order of frames managed and if the client should wait for`:ack` or not. For instance, this is the sequence of frames when the race happens:

```
-----> SENDING HEADERS
CLIENT Sent frame: {:type=>:settings, :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100]]}
CLIENT Sent frame: {:type=>:headers, :flags=>[:end_headers], :payload=>[[":scheme", "http"], [":method", "POST"], [":path", "/path"], ["host", "localhost"], ["content-length", "100000"]], :stream=>1}

-----> SENDING BODY
CLIENT Sent frame: {:type=>:data, :flags=>[], :payload=>"{BIG PAYLOAD OF 16384 BYTES}", :stream=>1}SERVER Sent frame: {:type=>:settings, :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100]]}
SERVER Received frame: {:length=>6, :type=>:settings, :flags=>[], :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100]]}
SERVER Sent frame: {:type=>:settings, :stream=>0, :payload=>[], :flags=>[:ack]}
SERVER Received frame: {:length=>22, :type=>:headers, :flags=>[:end_headers], :stream=>1, :payload=>"\x86\x83D\x84b\xB1\xA6\x7Ff\x86\xA0\xE4\x1D\x13\x9D\t\\\x84\b\x00\x00\x03"}
SERVER HEADERS: [[":scheme", "http"], [":method", "POST"], [":path", "/path"], ["host", "localhost"], ["content-length", "100000"]]
CLIENT Received frame: {:length=>6, :type=>:settings, :flags=>[], :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100]]}
CLIENT Sent frame: {:type=>:settings, :stream=>0, :payload=>[], :flags=>[:ack]}

*** HANGS ***
```

If I sleep in between sending headers and body:
```ruby
stream.headers(headers, end_stream: false)
sleep 1
stream.data(body, end_stream: true)
```
Then everything works, and this is the sequence is:

```
-----> SENDING HEADERS
CLIENT Sent frame: {:type=>:settings, :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100]]}
CLIENT Sent frame: {:type=>:headers, :flags=>[:end_headers], :payload=>[[":scheme", "http"], [":method", "POST"], [":path", "/path"], ["host", "localhost"], ["content-length", "100000"]], :stream=>1}
SERVER Sent frame: {:type=>:settings, :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100]]}
SERVER Received frame: {:length=>6, :type=>:settings, :flags=>[], :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100]]}
SERVER Sent frame: {:type=>:settings, :stream=>0, :payload=>[], :flags=>[:ack]}
SERVER Received frame: {:length=>22, :type=>:headers, :flags=>[:end_headers], :stream=>1, :payload=>"\x86\x83D\x84b\xB1\xA6\x7Ff\x86\xA0\xE4\x1D\x13\x9D\t\\\x84\b\x00\x00\x03"}
SERVER HEADERS: [[":scheme", "http"], [":method", "POST"], [":path", "/path"], ["host", "localhost"], ["content-length", "100000"]]
CLIENT Received frame: {:length=>6, :type=>:settings, :flags=>[], :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100]]}
CLIENT Sent frame: {:type=>:settings, :stream=>0, :payload=>[], :flags=>[:ack]}
CLIENT Received frame: {:length=>0, :type=>:settings, :flags=>[:ack], :stream=>0, :payload=>[]}
SERVER Received frame: {:length=>0, :type=>:settings, :flags=>[:ack], :stream=>0, :payload=>[]}

-----> SENDING BODY
CLIENT Sent frame: {:type=>:data, :flags=>[], :payload=>"{BIG PAYLOAD OF 16384 BYTES}", :stream=>1}
CLIENT Sent frame: {:type=>:data, :flags=>[], :payload=>"{BIG PAYLOAD OF 16384 BYTES}", :stream=>1}
SERVER Received frame: {:length=>16384, :type=>:data, :flags=>[], :stream=>1, :payload=>"{BIG PAYLOAD OF 16384 BYTES}"}
SERVER DATA: {BIG PAYLOAD OF 16384 BYTES}
SERVER Sent frame: {:type=>:window_update, :stream=>0, :increment=>16384}
SERVER Sent frame: {:type=>:window_update, :increment=>16384, :stream=>1}
CLIENT Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>0, :increment=>16384}
CLIENT Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>1, :increment=>16384}
CLIENT Sent frame: {:type=>:data, :flags=>[], :payload=>"{BIG PAYLOAD OF 16384 BYTES}", :stream=>1}
SERVER Received frame: {:length=>16384, :type=>:data, :flags=>[], :stream=>1, :payload=>"{BIG PAYLOAD OF 16384 BYTES}"}
SERVER DATA: {BIG PAYLOAD OF 16384 BYTES}
SERVER Sent frame: {:type=>:window_update, :stream=>0, :increment=>16384}
SERVER Sent frame: {:type=>:window_update, :increment=>16384, :stream=>1}
CLIENT Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>0, :increment=>16384}
CLIENT Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>1, :increment=>16384}
CLIENT Sent frame: {:type=>:data, :flags=>[], :payload=>"{BIG PAYLOAD OF 16384 BYTES}", :stream=>1}
SERVER Received frame: {:length=>16384, :type=>:data, :flags=>[], :stream=>1, :payload=>"{BIG PAYLOAD OF 16384 BYTES}"}
SERVER DATA: {BIG PAYLOAD OF 16384 BYTES}
SERVER Sent frame: {:type=>:window_update, :stream=>0, :increment=>16384}
SERVER Sent frame: {:type=>:window_update, :increment=>16384, :stream=>1}
CLIENT Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>0, :increment=>16384}
CLIENT Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>1, :increment=>16384}
CLIENT Sent frame: {:type=>:data, :flags=>[], :payload=>"{BIG PAYLOAD OF 16384 BYTES}", :stream=>1}
SERVER Received frame: {:length=>16384, :type=>:data, :flags=>[], :stream=>1, :payload=>"{BIG PAYLOAD OF 16384 BYTES}"}
SERVER DATA: {BIG PAYLOAD OF 16384 BYTES}
SERVER Sent frame: {:type=>:window_update, :stream=>0, :increment=>16384}
SERVER Sent frame: {:type=>:window_update, :increment=>16384, :stream=>1}
CLIENT Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>0, :increment=>16384}
CLIENT Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>1, :increment=>16384}
CLIENT Sent frame: {:type=>:data, :flags=>[], :payload=>"{BIG PAYLOAD OF 16384 BYTES}", :stream=>1}
SERVER Received frame: {:length=>16384, :type=>:data, :flags=>[], :stream=>1, :payload=>"{BIG PAYLOAD OF 16384 BYTES}"}
SERVER DATA: {BIG PAYLOAD OF 16384 BYTES}
SERVER Sent frame: {:type=>:window_update, :stream=>0, :increment=>16384}
SERVER Sent frame: {:type=>:window_update, :increment=>16384, :stream=>1}
CLIENT Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>0, :increment=>16384}
CLIENT Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>1, :increment=>16384}
CLIENT Sent frame: {:type=>:data, :flags=>[:end_stream], :payload=>"{PAYLOAD OF 1696 BYTES}", :stream=>1}
SERVER Received frame: {:length=>16384, :type=>:data, :flags=>[], :stream=>1, :payload=>"{BIG PAYLOAD OF 16384 BYTES}"}
SERVER DATA: {BIG PAYLOAD OF 16384 BYTES}
SERVER Sent frame: {:type=>:window_update, :stream=>0, :increment=>16384}
SERVER Sent frame: {:type=>:window_update, :increment=>16384, :stream=>1}
CLIENT Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>0, :increment=>16384}
SERVER Received frame: {:length=>1696, :type=>:data, :flags=>[:end_stream], :stream=>1, :payload=>"{PAYLOAD OF 1696 BYTES}"}
CLIENT Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>1, :increment=>16384}
SERVER DATA: {PAYLOAD OF 1696 BYTES}
SERVER Sent frame: {:type=>:window_update, :stream=>0, :increment=>1696}
SERVER Sent frame: {:type=>:window_update, :increment=>1696, :stream=>1}
CLIENT Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>0, :increment=>1696}
CLIENT Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>1, :increment=>1696}
SERVER Sent frame: {:type=>:headers, :flags=>[:end_headers], :payload=>[[":status", "200"], ["content-length", "11"], ["content-type", "text/plain"]], :stream=>1}
CLIENT Received frame: {:length=>14, :type=>:headers, :flags=>[:end_headers], :stream=>1, :payload=>"\x88\\\x0211_\x87I|\xA5\x8A\xE8\x19\xAA"}
SERVER Sent frame: {:type=>:data, :flags=>[:end_stream], :payload=>"response ok", :stream=>1}
CLIENT Received frame: {:length=>11, :type=>:data, :flags=>[:end_stream], :stream=>1, :payload=>"response ok"}
CLIENT Sent frame: {:type=>:window_update, :stream=>0, :increment=>11}
CLIENT Sent frame: {:type=>:window_update, :increment=>11, :stream=>1}
SERVER Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>0, :increment=>11}
SERVER Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>1, :increment=>11}
```
It looks like the client should wait all of the settings exchanges before sending data. Is this correct?

Obviously the `sleep 1` isn't a fix but I'm not sure what a client should be doing here.

Any input is welcome.

**Comment by ostinelli** [comment]
Got it, and [fixed it](https://github.com/ostinelli/net-http2/commit/189bb25f09abd6a5c472d50439045f169c7b415e).

Do you have an estimate when you will push the new gem version which includes your fixes?

Thank you.

**Comment by igrigorik** [comment]
Awesome, glad you tracked it down! 

Just released 0.8.2.

**Comment by ostinelli** [comment]
Awesome, thank you!

**Comment by HoneyryderChuck** [comment]
did you manage to solve this? I'm also having issues with the upload, specifically, the client manages to send the multipart request, the server gets it and sends the response frames, but the client times out.

**Comment by ostinelli** [comment]
See here: https://github.com/igrigorik/http-2/issues/92

**Comment by bw1109** [comment]
hey I am facing a similar kind of issue
while sending payload of 10k bytes
here's my error
Please help me with this.
Traceback (most recent call last):
  File "extratest.py", line 27, in <module>
    resp = conn.get_response()
  File "/export/home/bw1109/servtest/lib64/python3.7/site-packages/hyper/http20/connection.py", line 312, in get_response
    return HTTP20Response(stream.getheaders(), stream)
  File "/export/home/bw1109/servtest/lib64/python3.7/site-packages/hyper/http20/stream.py", line 230, in getheaders
    self._recv_cb(stream_id=self.stream_id)
  File "/export/home/bw1109/servtest/lib64/python3.7/site-packages/hyper/http20/connection.py", line 779, in _recv_cb
    self._single_read()
  File "/export/home/bw1109/servtest/lib64/python3.7/site-packages/hyper/http20/connection.py", line 669, in _single_read
    events = conn.receive_data(data)
  File "/export/home/bw1109/servtest/lib64/python3.7/site-packages/h2/connection.py", line 1531, in receive_data
    events.extend(self._receive_frame(frame))
  File "/export/home/bw1109/servtest/lib64/python3.7/site-packages/h2/connection.py", line 1554, in _receive_frame
    frames, events = self._frame_dispatch_table[frame.__class__](frame)
  File "/export/home/bw1109/servtest/lib64/python3.7/site-packages/h2/connection.py", line 1823, in _receive_rst_stream_frame
    stream_frames, stream_events = stream.stream_reset(frame)
  File "/export/home/bw1109/servtest/lib64/python3.7/site-packages/h2/stream.py", line 1232, in stream_reset
    events = self.state_machine.process_input(StreamInputs.RECV_RST_STREAM)
  File "/export/home/bw1109/servtest/lib64/python3.7/site-packages/h2/stream.py", line 131, in process_input
    return func(self, previous_state)
  File "/export/home/bw1109/servtest/lib64/python3.7/site-packages/h2/stream.py", line 416, in reset_on_closed_stream
    return self.recv_on_closed_stream(previous_state)
  File "/export/home/bw1109/servtest/lib64/python3.7/site-packages/h2/stream.py", line 338, in recv_on_closed_stream
    raise StreamClosedError(self.stream_id)
h2.exceptions.StreamClosedError: 1

**Comment by igrigorik** [comment]
@bw1109 this repo is for the Ruby http/2 library, your code is referencing a Python lib.. :)
